# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  # 股票价格（使用 HACS 安装的 yahoofinance 集成，快手 HK1024）
  - platform: yahoofinance
    scan_interval: 300
    show_trending_icon: true
    symbols:
      - 1024.HK

template:
  - trigger:
      - platform: event
        event_type: feedreader
    sensor:
      - name: "News Headline"
        unique_id: news_headline
        state: "{{ trigger.event.data.title }}"
