
services:
  home_assistant:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/workspace
      - ../config:/config
      - /run/dbus:/run/dbus:ro
    environment:
      # - http_proxy=
      # - https_proxy=
      # - all_proxy=
      - http_proxy=http://127.0.0.1:7897
      - https_proxy=http://127.0.0.1:7897
      - all_proxy=socks5://127.0.0.1:7897
      - TZ=Asia/Shanghai
    restart: unless-stopped
    privileged: true
    # user: user
    network_mode: host
    stdin_open: true
    tty: true
    
    # command: ["tail", "-f", "/dev/null"]
